name: Build & Preview MFE Host and Remote

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-remote:
    name: Build Recipes Remote
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: micro-frontends/recipes-remote

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build remote
        run: npm run build

  build-host:
    name: Build Shopping Host
    runs-on: ubuntu-latest
    needs: build-remote
    defaults:
      run:
        working-directory: micro-frontends/shopping-host

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build host
        run: npm run build
