name: Deploy Microfrontends to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [shopping-host, recipes-remote]

    defaults:
      run:
        working-directory: micro-frontends/${{ matrix.app }}

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the app
      - name: Build app
        run: npm run build

      # Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change to your region

      # Deploy to S3
      - name: Deploy to S3
        run: |
          if [ "${{ matrix.app }}" == "shopping-host" ]; then
            aws s3 sync ./dist s3://tastehub-shopping-host --delete --acl public-read
          else
            aws s3 sync ./dist s3://tastehub-recipes-remote --delete --acl public-read
          fi
